version: "2"
services:
  node:
    image: "node:alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - $(pwd)/:/home/node/app
    ports:
      - "8081:8081"
    command: "node app.js"